import { useUser } from '@auth0/nextjs-auth0/client'
import Head from 'next/head'

export default function Home() {
    const { user, error, isLoading } = useUser()

    if (isLoading) return <div>Loading...</div>
    if (error) return <div>{error.message}</div>

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <a href="/api/auth/login">Login</a>
                <a href="/api/auth/logout">Logout</a>

                {user && (
                    <div>
                        <h2>{user.name}</h2>
                        <p>{user.email}</p>
                    </div>
                )}
            </main>
        </>
    )
}
